version: "3"

services:
  app:
    environment:
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
    command: bash -c "
        poetry run python manage.py migrate
        && poetry run python manage.py runserver 0.0.0.0:8000
      "
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"